### ISSUE TITLE
Enable UBX passthrough

### ISSUE THREAD

**Issue by VirusPilot** [moshe-braner/SoftRF#9]
As already mentioned in Gitter, I am loosely involved in the development of Stratux, see https://github.com/b3nn0/stratux which typically is used as an RX device for multiple protocols. In the meantime the OGN Tracker as a TX device has been included, which also includes the possibility to configure the u-blox GPS in a way that it fits our purpose. Here is a list of changes to the default u-blox settings which we use for the OGN Tracker:
- enable GGA, RMC, VTG @ 5Hz
- enable GSA, GSV @ 1 Hz
- enable Beidou/Galileo e.g. for u-blox M8
- NMEA protocol version 4.0
- NMEA extended SV numbering

This simply requires that the UBX binary commands are passed through to the SoftRF GPS which currently is not the case. Do you think you can have a look into that? If that would work, we could even further think about remote configuration commands to change ICAO, Pilot name, Aircraft type ...

**Comment by moshe-braner** [comment]
Adding an ongoing stream of messages INTO the SoftRF device to be passed on to the GPS would be complicated.  But since you only need to configure the GPS on rare occasions, can perhaps add it into the Settings, so you can type something in there and it would be sent to the GPS when you click to "save" the settings.  If you send me your code for configuring the GPS, I can try and implement it in the settings screen.

**Comment by VirusPilot** [comment]
As a first shot I have "hardcoded" the u-blox settings in my SoftRF fork and it works quite nicely. I may add a global #define STRATUX. Also added changing AircraftID on the web interface.

**Comment by VirusPilot** [comment]
The u-blox and L76K related changes have been implemented and tested in my fork, I will create a PR for your fork soon.
